import { ReactNode } from "react";
import { auth } from "@/lib/server-api/auth";
import { redirect } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { SessionStoreProvider } from "@/component/provider/session-provider";
import "@/globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function ProtectedLayout({
    children
}: {
    children: ReactNode;
}) {
    const session = await auth();

    if (!session) {
        redirect("/login");
    }

    const messages = await getMessages(session.locale || "ko");
    const locale = session.locale || "ko";
    console.log("session:", session);

    return (
        <SessionStoreProvider initialState={{ session }}>
            <NextIntlClientProvider locale={locale} messages={messages}>
                <div className="flex w-full h-full">
                    <div className="w-[300px] border-r border-gray-200 p-4 fixed left-0 top-0 h-full">
                        sidebar{JSON.stringify(session)}
                    </div>
                    <div className="flex-1 p-4 ml-[300px]">
                        {children}
                    </div>
                </div>
            </NextIntlClientProvider>
        </SessionStoreProvider>
    );
}
